name: CI Main - Analytics Service
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker_build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Build Image
        run: make docker-build image_tag=${GITHUB_SHA}

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run Tests
        run: echo "Running tests..."


  dev-deploy:
    runs-on: self-hosted
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: raghudevopsb88/wmp-helm-v1
          path: helm
      - name: Helm Deploy
        run: make eks-deploy image_tag=${GITHUB_SHA}


  qa-deploy:
    runs-on: self-hosted
    needs: dev-deploy
    environment: qa
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA..."


  uat-deploy:
    runs-on: self-hosted
    needs: qa-deploy
    environment: uat
    steps:
      - name: Deploy to UAT
        run: echo "Deploying to UAT..."


  prod-deploy:
    runs-on: self-hosted
    needs: uat-deploy
    environment: prod
    steps:
      - name: Deploy to Production
        run: echo "Deploying to production..."

