name: CI - Analytics Service
on: [push]
jobs:
  docker_build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - run: env
      - name: Build Image
        run: make docker-build

  eks_deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: raghudevopsb88/wmp-helm-v1
          path: helm
      - name: Helm Deploy
        run: make eks-deploy


